# Generated by Django 3.2.6 on 2021-08-13 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_rename_group_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='prepod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.personal'),
        ),
    ]
