# Generated by Django 3.2.6 on 2021-08-13 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_course_prepod'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='news',
            new_name='new',
        ),
    ]
