# Generated by Django 3.2.6 on 2021-08-14 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_rename_new_new_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='new_post',
            new_name='novelty',
        ),
    ]
