# Generated by Django 3.2.6 on 2021-08-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_rename_new_post_novelty'),
    ]

    operations = [
        migrations.AddField(
            model_name='novelty',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
