# Generated by Django 3.2.6 on 2021-08-16 04:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0011_novelty_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Group',
        ),
    ]
