# Generated by Django 3.2.6 on 2021-08-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_group_type_cours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='type_cours',
            field=models.CharField(choices=[('R', 'Платные'), ('B', 'Бесплатные')], max_length=1, null=True),
        ),
    ]
