# Generated by Django 3.2.6 on 2021-08-16 11:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0017_auto_20210816_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='name',
        ),
        migrations.AddField(
            model_name='claim',
            name='name',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
