# Generated by Django 3.2.6 on 2021-08-16 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0018_auto_20210816_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='course',
        ),
        migrations.AddField(
            model_name='claim',
            name='course',
            field=models.ManyToManyField(to='manager.Course'),
        ),
        migrations.RemoveField(
            model_name='claim',
            name='name',
        ),
        migrations.AddField(
            model_name='claim',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
