# Generated by Django 3.2.6 on 2021-08-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0019_auto_20210816_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='qvant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('zag', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField()),
            ],
        ),
    ]
