# Generated by Django 3.2.6 on 2021-08-18 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0021_auto_20210818_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='type_cours',
        ),
        migrations.AddField(
            model_name='course',
            name='type_cours',
            field=models.CharField(choices=[('R', 'Квантум'), ('B', 'Курс')], max_length=1, null=True),
        ),
    ]
