# Generated by Django 3.2.6 on 2021-08-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0023_alter_course_type_cours'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='zag',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
