# Generated by Django 3.2.6 on 2021-08-18 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0024_auto_20210818_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='course',
        ),
        migrations.AddField(
            model_name='claim',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.course'),
        ),
    ]
