# Generated by Django 3.2.6 on 2021-08-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0025_auto_20210818_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='type_cours',
            field=models.CharField(choices=[('1', 'Квантум'), ('2', 'Курс')], max_length=1, null=True),
        ),
    ]
