# Generated by Django 3.2.6 on 2021-08-18 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0026_claim_type_cours'),
    ]

    operations = [
        migrations.DeleteModel(
            name='qvant',
        ),
    ]
