# Generated by Django 3.2.6 on 2021-08-22 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0028_auto_20210821_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('1', 'Понедельник'), ('2', 'Вторник'), ('3', 'Среда'), ('4', 'Четверг'), ('5', 'Пятница'), ('6', 'Суббота')], max_length=1, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='group',
            name='day_work',
        ),
        migrations.AddField(
            model_name='group',
            name='day_work',
            field=models.ManyToManyField(to='manager.timetable'),
        ),
    ]
