# Generated by Django 3.2.6 on 2021-08-22 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0029_auto_20210822_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='day',
            field=models.CharField(choices=[('Понедельник', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), ('Пятница', 'Пятница'), ('Суббота', 'Суббота')], max_length=12, null=True),
        ),
    ]
