# Generated by Django 3.2.6 on 2021-08-22 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0030_alter_timetable_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='name',
            field=models.CharField(blank=True, max_length=29),
        ),
    ]
