# Generated by Django 3.2.6 on 2021-08-22 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0032_auto_20210822_0938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetable',
            old_name='name',
            new_name='group',
        ),
    ]
