# Generated by Django 3.2.6 on 2021-08-22 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0033_rename_name_timetable_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='group',
        ),
        migrations.AddField(
            model_name='group',
            name='day_work',
            field=models.ManyToManyField(to='manager.timetable'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='name',
            field=models.CharField(blank=True, max_length=29),
        ),
    ]
